### ISSUE TITLE
How to get the yuv information of each frame.

### ISSUE THREAD

**Issue by zhw2590582** [ssilkin/bsparser#1]
Your project is so amazing, I want to ask if I can get YUV information from H264's nalu, I want to render it to the canvas.

**Comment by ssilkin** [comment]
bsparser only parses high level headers. You can decode H264 using ffmpeg (e.g. ffmpeg -i h264stream out.y4m) and then render YUV using https://ssilkin.github.io/yuv/

**Comment by zhw2590582** [comment]
Ok, thank you for your reply.
